export default [
  [
    {
      id: "adsada2",
      keybind: "1",
      src: "https://s3-us-west-2.amazonaws.com/s.cdpn.io/87792/fireball-red-1.png",
      name: "Fireball",
      cooldown: 10,
      globalCooldown: 1,
      isSelf: true,
    },
    {
      id: "adsada3",
      keybind: "2",
      src: "https://s3-us-west-2.amazonaws.com/s.cdpn.io/87792/evil-eye-eerie-3.png",
      name: "Evil Eye",
      cooldown: 10,
      globalCooldown: 1,
      isSelf: true,
    },
    {
      id: "adsada4",
      keybind: "3",
      src: "https://s3-us-west-2.amazonaws.com/s.cdpn.io/87792/protect-orange-3.png",
      name: "Protect",
      cooldown: 10,
      globalCooldown: 1,
      isSelf: true,
    },
    {
      id: "adsada5",
      keybind: "4",
      src: "https://s3-us-west-2.amazonaws.com/s.cdpn.io/87792/fireball-acid-3.png",
      name: "Acid Ball",
      cooldown: 10,
      globalCooldown: 1,
      isSelf: false,
    },
  ],
  [
    {
      id: "b1",
      keybind: "1",
      src: "/images/skills/10001.png",
      name: "Alt1",
      cooldown: 3,
      globalCooldown: 1,
    },
    {
      id: "b2",
      keybind: "2",
      src: "/images/skills/10002.png",
      name: "Alt2",
      cooldown: 3,
      globalCooldown: 1,
    },
    {
      id: "b3",
      keybind: "3",
      src: "/images/skills/10003.png",
      name: "Alt3",
      cooldown: 3,
      globalCooldown: 1,
    },
    {
      id: "b4",
      keybind: "4",
      src: "/images/skills/10004.png",
      name: "Alt4",
      cooldown: 3,
      globalCooldown: 1,
    },
  ],
];
